# Generated by Django 4.2.3 on 2023-07-25 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('POSTitle', models.CharField(max_length=250, verbose_name='Post Title')),
                ('POSSlug', models.SlugField(blank=True, null=True, verbose_name='Post Slug')),
                ('POSBody', models.TextField(verbose_name='Post Body')),
                ('POSPublish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publish  At')),
                ('POSCreated', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('POSUpdated', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('POSStatus', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2, verbose_name='Post Status')),
                ('POSAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-POSPublish'],
                'indexes': [models.Index(fields=['-POSPublish'], name='blog_post_POSPubl_3c5e6e_idx')],
            },
        ),
    ]
