# Generated by Django 4.2.3 on 2023-07-25 23:13

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('POSObjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
