# Generated by Django 4.2.3 on 2023-07-29 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_alter_post_posslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='POSAuthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COMName', models.CharField(max_length=80, verbose_name='Name')),
                ('COMEmail', models.EmailField(max_length=254, verbose_name='Email')),
                ('COMBody', models.TextField(verbose_name='Body')),
                ('COMCreated', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('COMUpdated', models.DateTimeField(auto_now=True, verbose_name='Update At')),
                ('COMActive', models.BooleanField(default=True, verbose_name='Comment Active')),
                ('COMPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='Post')),
            ],
            options={
                'ordering': ['COMCreated'],
                'indexes': [models.Index(fields=['COMCreated'], name='blog_commen_COMCrea_3ca7d8_idx')],
            },
        ),
    ]
